### PR TITLE
update State Template

### PR DESCRIPTION
**Pull request by kxc0re**
just two small style changes:
- use a const field for defaults
- use destructuring in the sample action

### CODE REVIEW

**Comment by kxc0re** [comment]
i wont do pr in the browser ever again :/ 

sorry for the spam

**Comment by splincode** [comment]
@markwhitfeld please see

@kxc0re rebase and merge commits

commit ->`fix(cli): update template`

**Comment by kxc0re** [comment]
it would probably be more consistent, when you destructure the payload too
```typescript
add({ getState, setState }: StateContext<{{pascalCase name}}StateModel>, { payload }: {{pascalCase name}}Action) { 
//..
}
```

**Comment by kxc0re** [comment]
did the destructuring of the payload too

**Comment by splincode** [comment]
Where?
image

**Review by splincode — APPROVED** [review]

**Pull request merged**
