### PR TITLE
Added the Injectable decorator to state template

### PR DESCRIPTION
**Pull request by mehmet-erim**
Added the Injectable decorator to state template for Ivy compatibility

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
The Travis CI build failed

**Comment by mehmet-erim** [comment]
Fixed 👍

**Comment by splincode** [comment]
@markwhitfeld please publish this package, I don't have permission for publish

**Comment by splincode** [comment]
@mehmet-erim @markwhitfeld ohh, sorry, I managed and published v2.0

**Pull request merged**
